import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Download, History, FileCheck, CheckCircle2 } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { handleError } from '@/lib/errorHandler';
import { formatCurrency } from '@/lib/utils';
import jsPDF from 'jspdf';

interface SavedForm {
  fullName?: string;
  personalDetails?: {
    fullName?: string;
  };
  timestamp: string;
  monthlySavings?: number;
  currentProvider?: string;
  newProvider?: string;
  newPlan?: string;
  signature?: string;
  documentId?: string;
  submissionId?: string;
}

interface SavedFormsProps {
  category: 'electricity' | 'cellular' | 'internet';
}

const categoryNames = {
  electricity: 'חשמל',
  cellular: 'סלולר',
  internet: 'אינטרנט'
};

export const SavedForms = ({ category }: SavedFormsProps) => {
  const [savedForms, setSavedForms] = useState<SavedForm[]>([]);
  const { toast } = useToast();

  const loadSavedForms = () => {
    const forms: SavedForm[] = [];
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (key?.startsWith(`provider-switch-${category}`) || key?.startsWith(`switch-${category}`)) {
        try {
          const data = JSON.parse(localStorage.getItem(key) || '{}');
          forms.push(data);
        } catch (error) {
          handleError(error, 'Loading saved forms');
        }
      }
    }
    setSavedForms(forms.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()));
  };

  const generateFormContent = (formData: SavedForm) => {
    const timestamp = new Date(formData.timestamp);
    return `טופס מעבר ספק ${categoryNames[category]} - מקורי
=====================================

נוצר: ${timestamp.toLocaleDateString('he-IL')} ${timestamp.toLocaleTimeString('he-IL')}
מזהה: ${formData.submissionId || formData.documentId}

פרטי הלקוח:
שם מלא: ${formData.fullName || formData.personalDetails?.fullName || 'לא צוין'}
מספק נוכחי: ${formData.currentProvider || 'לא צוין'}
לספק חדש: ${formData.newProvider || 'לא צוין'}
חבילה חדשה: ${formData.newPlan || 'לא צוין'}
חיסכון חודשי: ₪${formData.monthlySavings || 0}

חתימה דיגיטלית: ${formData.signature || 'לא זמין'}

מסמך זה נוצר על ידי מערכת השוואת ספקים
תאריך יצירה: ${new Date().toISOString()}`;
  };

  const downloadForm = (formData: SavedForm) => {
    try {
      // Create PDF document
      const pdf = new jsPDF();
      const timestamp = new Date(formData.timestamp);
      
      // Set up PDF
      pdf.setFontSize(18);
      pdf.setFont('helvetica', 'bold');
      pdf.text(`Provider Switch Form - ${categoryNames[category]}`, 20, 30);
      
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'normal');
      
      // Add content
      const content = [
        '',
        `Created: ${timestamp.toLocaleDateString('he-IL')} ${timestamp.toLocaleTimeString('he-IL')}`,
        `ID: ${formData.submissionId || formData.documentId || 'N/A'}`,
        '',
        'Customer Details:',
        `Full Name: ${formData.fullName || formData.personalDetails?.fullName || 'Not specified'}`,
        `Current Provider: ${formData.currentProvider || 'Not specified'}`,
        `New Provider: ${formData.newProvider || 'Not specified'}`,
        `New Plan: ${formData.newPlan || 'Not specified'}`,
        `Monthly Savings: ₪${formData.monthlySavings || 0}`,
        '',
        `Digital Signature: ${formData.signature ? 'Available' : 'Not available'}`,
        '',
        'This document was generated by the Provider Comparison System',
        `Creation Date: ${new Date().toISOString()}`
      ];
      
      let yPosition = 50;
      content.forEach(line => {
        if (line === '') {
          yPosition += 5;
        } else {
          pdf.text(line, 20, yPosition);
          yPosition += 7;
        }
      });
      
      // Save the PDF
      pdf.save(`provider-switch-${categoryNames[category]}-${timestamp.toLocaleDateString('he-IL')}.pdf`);

      toast({
        title: "הטופס הורד בהצלחה!",
        description: "הטופס נשמר במחשב שלך כקובץ PDF",
      });
    } catch (error) {
      handleError(error, 'Form download');
    }
  };

  return (
    <Card className="animate-fade-in">
      <CardHeader>
        <CardTitle className="flex items-center space-x-2 rtl:space-x-reverse">
          <History className="h-5 w-5 animate-scale-in" />
          <span>טפסים שמורים</span>
          <Button 
            variant="outline" 
            size="sm" 
            onClick={loadSavedForms}
            className="hover-scale"
          >
            רענן
          </Button>
        </CardTitle>
      </CardHeader>
      <CardContent>
        {savedForms.length === 0 ? (
          <div className="text-center p-8 text-muted-foreground animate-fade-in">
            <FileCheck className="h-12 w-12 mx-auto mb-4 opacity-50 animate-pulse" />
            <p>אין טפסים שמורים עדיין</p>
            <p className="text-sm">טפסים שתמלא יופיעו כאן</p>
          </div>
        ) : (
          <div className="space-y-4">
            {savedForms.map((form, index) => (
              <div 
                key={index} 
                className="flex items-center justify-between p-4 border rounded-lg hover-scale transition-all duration-300 animate-slide-up"
                style={{ animationDelay: `${index * 100}ms` }}
              >
                <div className="space-y-1">
                  <div className="flex items-center space-x-2 rtl:space-x-reverse">
                    <CheckCircle2 className="h-4 w-4 text-success animate-scale-in" />
                    <span className="font-medium">
                      טופס {categoryNames[category]} - {form.fullName || form.personalDetails?.fullName || 'לא שם'}
                    </span>
                  </div>
                  <div className="text-sm text-muted-foreground flex items-center space-x-4 rtl:space-x-reverse">
                    <span>נוצר: {new Date(form.timestamp).toLocaleDateString('he-IL')}</span>
                    {form.monthlySavings && (
                      <span className="text-success font-medium">
                        חיסכון: {formatCurrency(form.monthlySavings)}/חודש
                      </span>
                    )}
                  </div>
                </div>
                
                <Button 
                  variant="outline" 
                  size="sm"
                  onClick={() => downloadForm(form)}
                  className="hover-scale"
                >
                  <Download className="h-4 w-4 ml-2" />
                  הורד
                </Button>
              </div>
            ))}
          </div>
        )}
      </CardContent>
    </Card>
  );
};